<a href="https://colab.research.google.com/github/balnihat/yz_ornekler/blob/main/1_Numpy_k%C3%BCt%C3%BCphanesi_%C3%B6rnekleri.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Kütüphanesi Örnekleri

#### Kütüphaneyi içe aktarma

In [ ]:
import numpy as np

#### Numpy dizileri ve python listeleri

In [ ]:
liste=[1,5,7,10,15,20,22,30]
np_liste=np.array(liste)
print("liste verileri ",liste,"\n veri tipi",type(liste))
print("numpy liste verileri ",np_liste,"\n veri tipi",type(np_liste))

liste verileri  [1, 5, 7, 10, 15, 20, 22, 30] 
 veri tipi <class 'list'>
numpy liste verileri  [ 1  5  7 10 15 20 22 30] 
 veri tipi <class 'numpy.ndarray'>


####Listeden numpy dizisi oluşturma

In [ ]:
sayilar=np.array([1,5,7,10,15,20,22,30])
print("sayilar ",sayilar,"\n veri tipi",type(sayilar))

sayilar  [ 1  5  7 10 15 20 22 30] 
 veri tipi <class 'numpy.ndarray'>


#### Numpy dizilerine istenen verilere erişme

In [ ]:
print("ilk sayı=",sayilar[0])
print("ikinci sayı=",sayilar[1])
print("son sayı=",sayilar[-1])

ilk sayı= 1
ikinci sayı= 5
son sayı= 30


In [ ]:
print("tüm sayılar=",sayilar[:])
print("ilk iki sayı=",sayilar[0:2])
print("iki dört arası sayılar=",sayilar[1:4])
print("üçten sona kadar olan sayılar =",sayilar[2:])
yarisi=int(len(sayilar)/2)
print("ilk yarısı",sayilar[:yarisi])
print("diğer yarısı",sayilar[yarisi:])

tüm sayılar= [ 1  5  7 10 15 20 22 30]
ilk iki sayı= [1 5]
iki dört arası sayılar= [ 5  7 10]
üçten sona kadar olan sayılar = [ 7 10 15 20 22 30]
ilk yarısı [ 1  5  7 10]
diğer yarısı [15 20 22 30]


Numpy dizileri üretme

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(20,50,2)

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones(5)*10

array([10., 10., 10., 10., 10.])

In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
np.eye(4) # birim matris

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Rasgele sayı üretme

In [ ]:
np.random.rand(5)

array([0.53511266, 0.34799789, 0.13736947, 0.75478238, 0.28071511])

In [ ]:
np.random.rand(4,3)

array([[0.19858199, 0.4470885 , 0.384815  ],
       [0.96167992, 0.96526471, 0.73410878],
       [0.05761981, 0.47905692, 0.53333482],
       [0.15867293, 0.21099881, 0.3351488 ]])

In [ ]:
np.random.randn(10) # normal dağılıma göre rasgele sayı üretme

array([-0.31781842,  1.57620205,  1.2897002 ,  0.40861184, -0.70681136,
        0.04384442,  1.04292941,  0.41938332, -0.53484666, -1.09726195])

In [ ]:
np.random.randn(6,6) # normal dağılıma göre 2 boyutlu rasgele sayı üretme

array([[-1.49943245e-01,  1.21206516e+00,  9.35877430e-01,
         4.18140153e-01,  2.87222942e+00,  2.56133437e-01],
       [-7.67837840e-01, -3.22895872e-02, -1.97349303e+00,
         1.39133591e+00,  2.86068093e-03,  6.99524077e-01],
       [-1.73657272e-01, -7.21355983e-01,  6.75519049e-01,
         3.51897002e-03, -9.11744236e-01,  5.84482800e-01],
       [ 1.18850550e+00, -1.85298023e+00,  1.99115139e-01,
         3.61711002e-01, -6.26998530e-01, -7.33002217e-01],
       [-8.47834927e-01, -6.18089151e-01,  8.85532675e-01,
        -1.57004294e+00,  9.19255036e-01, -1.11353521e+00],
       [-1.19189948e+00, -9.81485889e-01, -1.98959084e-01,
        -1.62636038e+00,  1.27282321e-01,  1.01113823e+00]])

In [ ]:
np.random.randint(1,50) # 1(dahil) ile 50 (dahil değil) arası ragele  bir sayı üretme

47

In [ ]:
sayilar=np.random.randint(1,100,10) # 1(dahil) ile 100 (dahil değil) arası ragele  10 sayı üretme
print("sayilar dizisi eleman sayısı           =",sayilar.size)
print("sayilar dizisini şekli                 =",sayilar.shape)
print("sayilar dizinin en büyük değeri        =",sayilar.max())
print("sayilar dizinin en küçük değeri        =",sayilar.min())
print("sayilar dizisi en büyük değerin konumu =",sayilar.argmax())
print("sayilar dizisi en küçük değerin konumu =",sayilar.argmin())

sayilar dizisi eleman sayısı           = 10
sayilar dizisini şekli                 = (10,)
sayilar dizinin en büyük değeri        = 92
sayilar dizinin en küçük değeri        = 7
sayilar dizisi en büyük değerin konumu = 2
sayilar dizisi en küçük değerin konumu = 7


Numpy dizisinin boyutunu değiştirme

In [ ]:
print(sayilar.size)
sayilar.reshape(5,2) # 5 satır ve 2 sütun


10


array([[55, 45],
       [71, 64],
       [93, 80],
       [99, 68],
       [56, 35]])

In [ ]:
# referans yoluya veri alınca orjinal kopyada değişim olur
yeni_sayilar=np.random.randint(1,250,50)
print(yeni_sayilar)
yarisi=yeni_sayilar[:10]
print(yarisi)
yarisi[:]=50
print(yarisi)
print(yeni_sayilar)

[212 174 216 141 224 232  52  16 108 127  53 124  96  98 176 102  16 169
 143 174 219 141 227  97 126 205 189  29 165  93  83  84 134  43 167 227
  25  26  31  73   5 232   1 191 210  68 139 173 209  12]
[212 174 216 141 224 232  52  16 108 127]
[50 50 50 50 50 50 50 50 50 50]
[ 50  50  50  50  50  50  50  50  50  50  53 124  96  98 176 102  16 169
 143 174 219 141 227  97 126 205 189  29 165  93  83  84 134  43 167 227
  25  26  31  73   5 232   1 191 210  68 139 173 209  12]


In [ ]:
# copy yoluya veri alınca orjinal kopyada değişim olmaz
yeni_sayilar=np.random.randint(1,250,50)
print(yeni_sayilar)
yarisi=yeni_sayilar[:10]
yeni_yarisi=yarisi.copy()
print(yeni_yarisi)
yeni_yarisi[:]=50
print(yeni_yarisi)
print(yeni_sayilar)

[ 43 113  95  20 210 167 155 174 194 118  55  35   1  66 203 166  18 241
 226  60  38 239 150  94 210 193  69 139  61 201 212 209 136  64  65 167
 233 119 220  60 131 174 127 190 162 195  52  60  59 166]
[ 43 113  95  20 210 167 155 174 194 118]
[50 50 50 50 50 50 50 50 50 50]
[ 43 113  95  20 210 167 155 174 194 118  55  35   1  66 203 166  18 241
 226  60  38 239 150  94 210 193  69 139  61 201 212 209 136  64  65 167
 233 119 220  60 131 174 127 190 162 195  52  60  59 166]


In [ ]:
ornek_sayilar=np.random.randint(1,250,20).reshape(5,4)
ornek_sayilar

array([[ 41, 194,  22, 188],
       [117, 103,  32, 231],
       [  2, 157, 212, 225],
       [161, 111, 159, 243],
       [ 37,  80,  19,   4]])

Çok boyutlu dizilerde seçim işlemi

In [ ]:
print("ilk satır",ornek_sayilar[0])
print("ilk değer",ornek_sayilar[0][0])
print("son değer",ornek_sayilar[4][3])
print("son değer",ornek_sayilar[-1][-1])

ilk satır [ 41 194  22 188]
ilk değer 41
son değer 4
son değer 4
son değer [[  2 157 212 225]]


In [ ]:
print("ilk değer",ornek_sayilar[0,0])
print("son değer",ornek_sayilar[4,3])
print("son değer",ornek_sayilar[-1,-1])
print("son değer\n",ornek_sayilar[1:3,1:3])

ilk değer 41
son değer 4
son değer 4
son değer
 [[103  32]
 [157 212]]


Koşula bağlı seçim işlemleri

In [ ]:
#Koşul kontrolü 10 dan büyük sayılar
ornek_sayilar> 10

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True, False]])

In [ ]:
#Koşul kontrolü 30 dan küçük sayılar
ornek_sayilar< 30

array([[False, False,  True, False],
       [False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True]])

In [ ]:
#Koşullu seçim 10 dan büyük sayılar
ornek_sayilar[ornek_sayilar> 10]

array([ 41, 194,  22, 188, 117, 103,  32, 231, 157, 212, 225, 161, 111,
       159, 243,  37,  80,  19])

In [ ]:
#Koşullu seçim 30 dan küçük sayılar
ornek_sayilar[ornek_sayilar< 30]

array([22,  2, 19,  4])

In [ ]:
#Koşullu seçim 30 dan küçük ve 10 dan büyük sayılar parantez önemli!!
ornek_sayilar[(ornek_sayilar< 30) & (ornek_sayilar> 10)]

array([22, 19])

Numpy dizilerinde işlemler

In [ ]:
yeni_sayilar=np.random.randint(1,50,15)
yeni_sayilar

array([27, 26, 46,  1,  4, 24, 47,  9, 49, 18, 25,  3, 26, 33, 38])

In [ ]:
print("Sayılar=",yeni_sayilar)
print("Toplam= ",yeni_sayilar+yeni_sayilar)
print("Fark= ",yeni_sayilar-yeni_sayilar)
print("Çarpım= ",yeni_sayilar*yeni_sayilar)
print("Bölme= ",yeni_sayilar/yeni_sayilar)
print("Bölümünden kalan= ",yeni_sayilar%yeni_sayilar)

Toplam=  [54 52 92  2  8 48 94 18 98 36 50  6 52 66 76]
Fark=  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Çarpım=  [ 729  676 2116    1   16  576 2209   81 2401  324  625    9  676 1089
 1444]
Bölme=  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Bölümünden kalan=  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
print("Sayılar=",yeni_sayilar)
print("50 fazlası= ",yeni_sayilar+50)
print("50 eksiği= ",yeni_sayilar-50)
print("2 katı= ",yeni_sayilar*2)
print("yarısı= ",yeni_sayilar/2)

Sayılar= [27 26 46  1  4 24 47  9 49 18 25  3 26 33 38]
50 fazlası=  [77 76 96 51 54 74 97 59 99 68 75 53 76 83 88]
50 eksiği=  [-23 -24  -4 -49 -46 -26  -3 -41  -1 -32 -25 -47 -24 -17 -12]
2 katı=  [54 52 92  2  8 48 94 18 98 36 50  6 52 66 76]
yarısı=  [13.5 13.  23.   0.5  2.  12.  23.5  4.5 24.5  9.  12.5  1.5 13.  16.5
 19. ]


In [ ]:
yeni_sayilar*yeni_sayilar

array([ 729,  676, 2116,    1,   16,  576, 2209,   81, 2401,  324,  625,
          9,  676, 1089, 1444])

In [ ]:
print("Sayılar=",yeni_sayilar)
print("Sinüs değerleri=",np.sin(yeni_sayilar))
print("Kosinüs değerleri=",np.cos(yeni_sayilar))
print("Tanjant değerleri=",np.tan(yeni_sayilar))
print("Logaritmik değerleri=",np.log(yeni_sayilar))

Sayılar= [27 26 46  1  4 24 47  9 49 18 25  3 26 33 38]
Sinüs değerleri= [ 0.95637593  0.76255845  0.90178835  0.84147098 -0.7568025  -0.90557836
  0.12357312  0.41211849 -0.95375265 -0.75098725 -0.13235175  0.14112001
  0.76255845  0.99991186  0.29636858]
Kosinüs değerleri= [-0.29213881  0.64691932 -0.43217794  0.54030231 -0.65364362  0.42417901
 -0.99233547 -0.91113026  0.30059254  0.66031671  0.99120281 -0.9899925
  0.64691932 -0.01327675  0.95507364]
Tanjant değerleri= [ -3.2737038    1.17875355  -2.08661353   1.55740772   1.15782128
  -2.1348967   -0.12452757  -0.45231566  -3.17290855  -1.13731371
  -0.13352641  -0.14254654   1.17875355 -75.3130148    0.31030966]
Logaritmik değerleri= [3.29583687 3.25809654 3.8286414  0.         1.38629436 3.17805383
 3.8501476  2.19722458 3.8918203  2.89037176 3.21887582 1.09861229
 3.25809654 3.49650756 3.63758616]
